### ISSUE TITLE
1 - A, B, C [Modelagem e representação]

### ISSUE THREAD

**Issue by gabriosilva** [2023M5T1-Inteli/grupo3#1]
- [x] a) Qual o contexto do problema a ser resolvido (peso 1)
- [x] b) Quais os dados disponíveis (peso 1)
- [x] c) Qual o objetivo do problema (peso 1)

**Comment by gabriosilva** [comment]
Data de entrega - 03/02

**Comment by IaagoTavares** [comment]
https://docs.google.com/document/d/1tw2sgzEzcuUPzq3uVnzkJcTsCSNgwOywymCX6LDBWrQ/edit?usp=sharing
