### ISSUE TITLE
1. Contexto da Indústria e forças de porter [Entendimento de Negócio]

### ISSUE THREAD

**Issue by gbcarneiro** [2023M5T1-Inteli/grupo3#2]
- [ ] 1. Contexto da indústria (principais players, modelos de negócio, tendências) (peso 2) - O aluno deve construir o modelo de 5 Forças do Porter e fornecer informações sobre a concorrência (mínimo 3 players - 1 parágrafo; modelo de negócio - 1 parágrafo, e tendências - 1 parágrafo). Considere o setor do parceiro.

**Comment by gabriosilva** [comment]
Data de entrega - 03/02

**Comment by dtonavitor** [comment]
https://docs.google.com/document/d/1fVA5Z3D-hlwU1E7Sv3AitQYaMIJuH3tz3T-AWzYX8wc/edit
