### ISSUE TITLE
5. Matriz de Riscos do Projeto [Entendimento de Negócio]

### ISSUE THREAD

**Issue by Lederback** [2023M5T1-Inteli/grupo3#7]
- [ ] 5. Matriz de Riscos (peso 2) - A Matriz de Risco deve ser desenhada considerando o projeto que os alunos estão criando. Deve ser entregue no template disponível no drive da turma.

**Comment by gabriosilva** [comment]
Data de entrega - 03/02

**Comment by Lederback** [comment]
https://docs.google.com/presentation/d/1dXytxachPhXRCdA7pOvhVyAEGeGLNPOdF0axqOkaZF0/edit?pli=1#slide=id.p
